export 'admin/create_category_view.dart';
export 'admin/create_local_view.dart';
export 'admin/create_role_view.dart';
export 'admin/create_table_view.dart';
export 'homes/business_dashboard_view.dart';
export 'local_products_view.dart';
export 'publics/login_view.dart';
export 'admin/register_view.dart';
export 'publics/splash_view.dart';
export 'homes/show_tables_view.dart';
export 'show_table_detail_view.dart';
export 'pre_order_account_view.dart';
// TESTING
export 'test_routes_view.dart';
