// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9yH9Xh8IkYBPNUji0ZYTZaywTG3GFWMA',
    appId: '1:979020451369:web:f8b973b672ff1b13991638',
    messagingSenderId: '979020451369',
    projectId: 'app-plaza-24913',
    authDomain: 'app-plaza-24913.firebaseapp.com',
    storageBucket: 'app-plaza-24913.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtb4EfWetzhyB_a7-wHjvLRfaKV6dDGi8',
    appId: '1:979020451369:android:f9034f269a226d11991638',
    messagingSenderId: '979020451369',
    projectId: 'app-plaza-24913',
    storageBucket: 'app-plaza-24913.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9yH9Xh8IkYBPNUji0ZYTZaywTG3GFWMA',
    appId: '1:979020451369:web:457ccb42ad004de6991638',
    messagingSenderId: '979020451369',
    projectId: 'app-plaza-24913',
    authDomain: 'app-plaza-24913.firebaseapp.com',
    storageBucket: 'app-plaza-24913.firebasestorage.app',
  );
}
